# Use this file to create a new docker image derived from the standard datalab image

FROM gcr.io/cloud-datalab/datalab:latest
MAINTAINER AquaBiota <mapcloud@aquabiota.se>

# AquaBiota requirements
ENV GDAL_DATA $DATALAB_CONDA_DIR/share/gdal/
ENV GEOS_DIR $DATALAB_CONDA_DIR
ENV PATH $PATH:$GDAL_DATA

ENV R_BASE_VERSION 3.5.1


RUN apt-get -y update && apt-get -y dist-upgrade && \
apt-get install -y --no-install-recommends \
ed \
fonts-texgyre \
fonts-dejavu \
gfortran \
gcc \
less \
libatlas-base-dev \
liblapack-dev \
libcurl4-gnutls-dev \
libpng-dev \
libsnappy-dev \
libssl-dev \
libxft-dev \
libxml2-dev \
libssl-dev \
python-dev \
python-setuptools \
python-zmq \
tzdata \
vim-tiny \
 && conda config --system --append channels IOOS \
 && conda config --system --append channels r \
 && conda install --name $PYTHON_3_ENV --quiet -c conda-forge --yes gdal && \
conda install --name $PYTHON_3_ENV -c conda-forge --quiet --yes \
fiona \
folium \
geopandas \
scipy-sugar \
tinydb \
bcrypt \
passlib \
libgdal \
geopy \
rasterio \
ipyleaflet \
bqplot \
cmocean \
cartopy \
iris \
shapely \
pyproj \
pyyaml \
xmltodict \
jupyterlab \
google-api-python-client \
&& source activate $PYTHON_3_ENV \
&& pip install --upgrade-strategy only-if-needed s2sphere google\
&& pip install --upgrade-strategy only-if-needed jupyter_nbextensions_configurator jupyter_contrib_nbextensions && \
    jupyter contrib nbextension install --user && \
    jupyter nbextensions_configurator enable --user  && \

    conda install -c conda-forge --quiet --yes google-api-python-client r-base r-irkernel r-irdisplay r-pbdzmq r-uuid r-digest r-rgdal r-plyr r-devtools r-tidyverse r-shiny r-rmarkdown r-forecast r-rsqlite r-reshape2 r-caret r-rcurl r-crayon r-randomforest r-htmltools r-sparklyr r-htmlwidgets r-hexbin r-rzmq  r-ggplot2 r-nloptr  r-broom  r-dplyr  r-spatial  r-jsonlite  r-stringr  r-data.table r-hmisc r-car r-psych  r-mgcv  r-rocr r-raster  r-leaflet  r-proc  r-nnet  r-rpart  r-mass r-repr  r-ggthemes  r-sqldf  r-geosphere  r-xml  r-xml2  r-abind  r-gbm  r-gam  r-gamlss r-rjsonio r-dt\

&& conda install rpy2

COPY rpackages.R $DATALAB_CONDA_DIR/rpackages.R
RUN echo "source /usr/local/rpackages.R"

# RUN R -e 'install.packages("biomod2", dependencies = TRUE)'
