# Use this file to create a new docker image derived from the standard datalab image

FROM gcr.io/cloud-datalab/datalab:latest
#MAINTAINER Your Name <youremail@example.com>

# The following line will install package xlrd, as an example
RUN pip install xlrd


RUN conda install --quiet --yes \

geopandas==0.2.1 \
jsontableschema-pandas==0.5.0 \
scipy-sugar==1.0.8 \
tinydb==3.11.1 \
bcrypt==3.1.4 \
passlib==1.7.1 \
libgdal==2.3.2 \
geopy==1.17.0 \
folium==0.6.0 \
rasterio==1.0.8 \
ipyleaflet==0.9.1 \
bqplot==0.11.1 \
cmocean==1.2 \
cartopy==0.16.0 \
iris==2.2.0 \
shapely==1.6.4 \
pyproj==1.9.5.1 \
fiona==1.7.1.3 \
xmltodict==0.11.0 \
gdal==2.3.2 \
r-irkernel==0.8.2 \
r-gdal==1.3_6 \
rpy2==2.9.4 \
r-base==3.5.1 \
r-plyr==1.8.4 \
r-devtools==1.13.6 \
r-tidyverse==1.2.1 \
r-shiny==1.1.0 \
r-rmarkdown==1.10 \
r-forecast==8.4 \
r-rsqlite==2.1.1 \
r-reshape2==1.4.3 \
r-caret==6.0_80 \
r-rcurl==1.95_4.11 \
r-crayon==1.3.4 \
r-randomforest==4.6_14 \
r-htmltools==0.3.6 \
r-sparklyr==0.8.4 \
r-htmlwidgets==1.2 \
r-hexbin==1.27.2 \
r-rzmq==0.9.3  \
r-ggplot2==3.0.0 \
r-nloptr==1.0.4  \
r-broom==0.5.0  \
r-dplyr==0.7.6  \
r-spatial==7.3_11  \
r-jsonlite==1.5  \
r-stringr==1.3.1  \
r-data.table==1.11.4 \
r-hmisc==4.1_1 \
r-car==3.0_0 \
r-psych==1.8.4  \
r-mgcv==1.8_24  \
r-rocr==1.0_7 \
r-raster==2.6_7  \
r-leaflet==2.0.1  \
r-proc==1.12.1  \
r-nnet==7.3_12  \
r-rpart==4.1_13  \
r-mass==7.3_50 \
r-repr==0.15  \
r-irdisplay==0.5.0  \
r-ggthemes==4.0.1  \
r-sqldf==0.4_10  \
r-geosphere==1.5_7  \
r-xml==3.98_1.12  \
r-xml2==1.2.0  \
r-abind==1.4_5  \
r-gbm==2.1.4  \
r-gam==1.16  \
r-gamlss==5.1_2
